set(CUSTOMIZE_BUILD
    ON
    CACHE BOOL "" FORCE)

set(SUPPORT_BUSY_WAIT_LOOP
    OFF
    CACHE BOOL "" FORCE)

set(SUPPORT_CAMERA_SYSTEM
    OFF
    CACHE BOOL "" FORCE)

set(SUPPORT_CLANGD
    ON
    CACHE BOOL "" FORCE)

set(SUPPORT_COMPRESSION_API
    OFF
    CACHE BOOL "" FORCE)

set(SUPPORT_CUSTOM_FRAME_CONTROL
    OFF
    CACHE BOOL "" FORCE)

set(SUPPORT_DEFAULT_FONT
    ON
    CACHE BOOL "" FORCE)

set(SUPPORT_EVENTS_AUTOMATION
    OFF
    CACHE BOOL "" FORCE)

set(SUPPORT_EVENTS_WAITING
    OFF
    CACHE BOOL "" FORCE)

set(SUPPORT_FILEFORMAT_ASTC
    OFF
    CACHE BOOL "" FORCE)

set(SUPPORT_FILEFORMAT_BMP
    OFF
    CACHE BOOL "" FORCE)

set(SUPPORT_FILEFORMAT_DDS
    OFF
    CACHE BOOL "" FORCE)

set(SUPPORT_FILEFORMAT_FLAC
    OFF
    CACHE BOOL "" FORCE)

set(SUPPORT_FILEFORMAT_FNT
    OFF
    CACHE BOOL "" FORCE)

set(SUPPORT_FILEFORMAT_GIF
    OFF
    CACHE BOOL "" FORCE)

set(SUPPORT_FILEFORMAT_GLTF
    OFF
    CACHE BOOL "" FORCE)

set(SUPPORT_FILEFORMAT_HDR
    OFF
    CACHE BOOL "" FORCE)

set(SUPPORT_FILEFORMAT_IQM
    OFF
    CACHE BOOL "" FORCE)

set(SUPPORT_FILEFORMAT_JPG
    OFF
    CACHE BOOL "" FORCE)

set(SUPPORT_FILEFORMAT_KTX
    OFF
    CACHE BOOL "" FORCE)

set(SUPPORT_FILEFORMAT_M3D
    OFF
    CACHE BOOL "" FORCE)

set(SUPPORT_FILEFORMAT_MOD
    OFF
    CACHE BOOL "" FORCE)

set(SUPPORT_FILEFORMAT_MP3
    OFF
    CACHE BOOL "" FORCE)

set(SUPPORT_FILEFORMAT_MTL
    OFF
    CACHE BOOL "" FORCE)

set(SUPPORT_FILEFORMAT_OBJ
    OFF
    CACHE BOOL "" FORCE)

set(SUPPORT_FILEFORMAT_OGG
    OFF
    CACHE BOOL "" FORCE)

set(SUPPORT_FILEFORMAT_PIC
    OFF
    CACHE BOOL "" FORCE)

set(SUPPORT_FILEFORMAT_PKM
    OFF
    CACHE BOOL "" FORCE)

set(SUPPORT_FILEFORMAT_PNG
    ON
    CACHE BOOL "" FORCE)

set(SUPPORT_FILEFORMAT_PNM
    OFF
    CACHE BOOL "" FORCE)

set(SUPPORT_FILEFORMAT_PSD
    OFF
    CACHE BOOL "" FORCE)

set(SUPPORT_FILEFORMAT_PVR
    OFF
    CACHE BOOL "" FORCE)

set(SUPPORT_FILEFORMAT_QOA
    OFF
    CACHE BOOL "" FORCE)

set(SUPPORT_FILEFORMAT_QOI
    OFF
    CACHE BOOL "" FORCE)

set(SUPPORT_FILEFORMAT_SVG
    OFF
    CACHE BOOL "" FORCE)

set(SUPPORT_FILEFORMAT_TGA
    OFF
    CACHE BOOL "" FORCE)

set(SUPPORT_FILEFORMAT_TTF
    OFF
    CACHE BOOL "" FORCE)

set(SUPPORT_FILEFORMAT_VOX
    OFF
    CACHE BOOL "" FORCE)

set(SUPPORT_FILEFORMAT_WAV
    OFF
    CACHE BOOL "" FORCE)

set(SUPPORT_FILEFORMAT_XM
    OFF
    CACHE BOOL "" FORCE)

set(SUPPORT_FONT_ATLAS_WHITE_REC
    OFF
    CACHE BOOL "" FORCE)

set(SUPPORT_GESTURES_SYSTEM
    OFF
    CACHE BOOL "" FORCE)

set(SUPPORT_GIF_RECORDING
    OFF
    CACHE BOOL "" FORCE)

set(SUPPORT_IMAGE_EXPORT
    OFF
    CACHE BOOL "" FORCE)

set(SUPPORT_IMAGE_GENERATION
    OFF
    CACHE BOOL "" FORCE)

set(SUPPORT_IMAGE_MANIPULATION
    ON
    CACHE BOOL "" FORCE)

set(SUPPORT_MESH_GENERATION
    OFF
    CACHE BOOL "" FORCE)

set(SUPPORT_MODULE_RAUDIO
    OFF
    CACHE BOOL "" FORCE)

set(SUPPORT_MODULE_RMODELS
    OFF
    CACHE BOOL "" FORCE)

set(SUPPORT_MODULE_RSHAPES
    ON
    CACHE BOOL "" FORCE)

set(SUPPORT_MODULE_RTEXT
    ON
    CACHE BOOL "" FORCE)

set(SUPPORT_MODULE_RTEXTURES
    ON
    CACHE BOOL "" FORCE)

set(SUPPORT_MOUSE_GESTURES
    OFF
    CACHE BOOL "" FORCE)

set(SUPPORT_QUADS_DRAW_MODE
    ON
    CACHE BOOL "" FORCE)

set(SUPPORT_RPRAND_GENERATOR
    OFF
    CACHE BOOL "" FORCE)

set(SUPPORT_SCREEN_CAPTURE
    OFF
    CACHE BOOL "" FORCE)

set(SUPPORT_SSH_KEYBOARD_RPI
    ON
    CACHE BOOL "" FORCE)

set(SUPPORT_STANDARD_FILEIO
    OFF
    CACHE BOOL "" FORCE)

set(SUPPORT_TEXT_MANIPULATION
    ON
    CACHE BOOL "" FORCE)

set(SUPPORT_TRACELOG
    ON
    CACHE BOOL "" FORCE)

set(SUPPORT_WINMM_HIGHRES_TIMER
    ON
    CACHE BOOL "" FORCE)

set(USE_AUDIO
    OFF
    CACHE BOOL "" FORCE)
